import type { Lang } from '@/config'
import type { Metadata } from 'next'
import { Header } from '@/components/header'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { LANGS } from '@/config'
import localFont from 'next/font/local'
import '../globals.css'

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})

const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return LANGS
}

export default async function Root({
  children,
  params,
}: Readonly<{
  params: Promise<{ lang: Lang }>
  children: React.ReactNode
}>) {
  const { lang } = await params

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header lang={lang} />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  )
}
