import type { Metadata } from 'next'
import type { LayoutProps } from '../types'
import { Header } from '@/components/header'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { type Language, languages } from '@/dictionaries/settings'
import { EnumLanguage } from '@devfolio/enum'
import { Lora, Noto_Sans_SC } from 'next/font/google'
import './globals.css'
import '@/assets/style/intro.css'

const lora = Lora({ subsets: ['latin'], display: 'swap' })
const notoSansSC = Noto_Sans_SC({ subsets: ['latin', 'vietnamese'], display: 'swap' })
const fonts = {
  [EnumLanguage.US]: lora,
  [EnumLanguage.CN]: notoSansSC,
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return languages.map(lang => ({ lang }))
}

export default async function Root({ children, params }: LayoutProps) {
  const { lang } = await params

  return (
    <html lang={lang} className={fonts[lang].className}>
      <body className="antialiased">
        <Header lang={lang} />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  )
}
